/**
 * Storage type generation utilities.
 *
 * Generates TypeScript declaration files with typed overloads for:
 * - DatabaseStorage.open() and get() - validates database names at compile time
 * - DirectoryStorage.open() - validates directory names at compile time
 *
 * Based on configurations in shovel.json.
 */

import {loadRawConfig} from "./config.js";

/**
 * Information about a database discovered from shovel.json.
 */
export interface DatabaseInfo {
	/** Database name from shovel.json */
	name: string;
	/** Adapter module path */
	adapter: string;
}

/**
 * Discover databases from the project's shovel.json.
 *
 * @param projectRoot - Root directory of the project
 * @returns Array of discovered databases
 */
export function discoverDatabases(projectRoot: string): DatabaseInfo[] {
	const databases: DatabaseInfo[] = [];
	const config = loadRawConfig(projectRoot);

	if (config.databases) {
		for (const [name, dbConfig] of Object.entries(config.databases)) {
			databases.push({
				name,
				adapter: dbConfig.adapter,
			});
		}
	}

	return databases;
}

/**
 * Discover all directory names from project config.
 *
 * @param projectRoot - Root directory of the current project
 * @returns Array of directory names
 */
export function discoverDirectoryNames(projectRoot: string): string[] {
	const config = loadRawConfig(projectRoot);
	if (!config.directories) {
		return [];
	}
	return Object.keys(config.directories);
}

/**
 * Generate TypeScript declaration file with typed overloads for storage APIs.
 *
 * @param databases - Array of database info from discoverDatabases
 * @param directoryNames - Array of directory names from discoverDirectoryNames
 * @param outDir - Output directory where shovel.d.ts will be written
 * @returns Generated TypeScript declaration file content, or empty string if nothing to generate
 */
export function generateStorageTypes(
	databases: DatabaseInfo[],
	directoryNames: string[],
	outDir: string,
): string {
	if (databases.length === 0 && directoryNames.length === 0) {
		return "";
	}

	const imports: string[] = [];
	const sections: string[] = [];

	// Generate database type (union of valid names)
	if (databases.length > 0) {
		imports.push(`import type {Database} from "@b9g/zen";`);
		imports.push(`import type {DatabaseUpgradeEvent} from "@b9g/platform";`);

		const dbUnion = databases.map((db) => `"${db.name}"`).join(" | ");
		sections.push(`  /**
   * Valid database names from shovel.json.
   * Using an invalid name will cause a TypeScript error.
   */
  type ValidDatabaseName = ${dbUnion};

  interface DatabaseStorage {
    /** Open a database at a specific version, running migrations if needed */
    open(
      name: ValidDatabaseName,
      version: number,
      onUpgrade?: (event: DatabaseUpgradeEvent) => void,
    ): Promise<Database>;
    /** Get an already-opened database (throws if not opened) */
    get(name: ValidDatabaseName): Database;
    /** Close a specific database */
    close(name: ValidDatabaseName): Promise<void>;
    /** Close all databases */
    closeAll(): Promise<void>;
  }`);
	}

	// Generate directory type (union of valid names)
	if (directoryNames.length > 0) {
		const dirUnion = directoryNames.map((n) => `"${n}"`).join(" | ");
		sections.push(`  /**
   * Valid directory names from shovel.json.
   * Using an invalid name will cause a TypeScript error.
   */
  type ValidDirectoryName = ${dirUnion};

  interface DirectoryStorage {
    open(name: ValidDirectoryName): Promise<FileSystemDirectoryHandle>;
    has(name: ValidDirectoryName): Promise<boolean>;
  }`);
	}

	return `// Generated by Shovel - DO NOT EDIT
// This file provides typed overloads for self.databases and self.directories
${imports.join("\n")}

declare global {
${sections.join("\n\n")}
}

export {};
`;
}

/**
 * @deprecated Use generateStorageTypes instead
 */
export function generateDatabaseTypes(
	databases: DatabaseInfo[],
	outDir: string,
): string {
	return generateStorageTypes(databases, [], outDir);
}
